# Generated by Django 5.2.7 on 2025-10-24 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('shop', '0003_alter_order_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расходы')),
                ('orders', models.ManyToManyField(blank=True, to='shop.order', verbose_name='Заказы, учтённые в отчёте')),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.DeleteModel(
            name='OrderAnalytics',
        ),
    ]
