# Generated by Django 5.2.7 on 2025-10-24 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_salesreport_delete_orderanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='name',
            field=models.CharField(default='Старый отчет', max_length=200, verbose_name='Название отчёта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreport',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, чьи заказы включены'),
        ),
    ]
