# Generated by Django 5.2.7 on 2025-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_consent_given',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя Telegram (Управленческий бот)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_agreed_to_pdn',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн для Telegram (Пользовательский бот)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден через Telegram (Пользовательский бот)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя Telegram (Пользовательский бот)'),
        ),
    ]
