# Generated by Django 5.2.7 on 2025-10-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTelegramConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_consent_given',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_agreed_to_pdn',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн для Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден через Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя Telegram'),
        ),
    ]
