# Generated by Django 5.2.7 on 2025-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingtelegramconsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя Telegram (Управленческий бот)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_agreed_to_pdn',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн для Telegram (Пользовательский бот)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден через Telegram (Пользовательский бот)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя Telegram (Пользовательский бот)'),
        ),
    ]
