# Generated by Django 5.2.7 on 2025-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Платёж не прошёл'), ('cancelled', 'Платёж отменён')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
